### ISSUE TITLE
I propose to use cloaks

### ISSUE THREAD

**Issue by gmcclins** [hashbang/docker-unrealircd#4]
I understand that if log in using the #!hashbang shell the only IP address that is available via whois is that of the hashang server. I've noticed a lot that people connect from outside shell (not sure why), and this results in a minor leak of ISP info. I understand this is not that major, or at least I don't believe it to be, since it don't show as much info as places such as freenode.

But this got me to thinking. Since HostServ is available, if this is the right thing needed for cloaks. I propose to use it. My thought here is not to create some kind of ranking in place (if that is even the right choice of word), but to assign everyone a cloak based on level of contribution and if possible, have this vhost/cloak assigned automatically at account creation as most users may not request one.

I was thinking along the lines of 

hashbang/admins
hashbang/user
hashbang/contributers

or something like that, so I guess it would be a group cloack. With hashbang/user being the default for new users/current non-contributors. Thoughts?

**Comment by ghost** [comment]
I'm not sure about using HostServ, but I turned off the reverse DNS system, so users should have only their IP, hashed, displayed. Maybe users can get a HostServ cloak if they want, I'm not yet sure if I'm allowed to make that judgement.

**Comment by RyanSquared** [comment]
I believe we're now using hashes for connecting users.
